# Site settings
title: Sinjoy Saha
description: Portfolio of Sinjoy Saha
#baseurl: "/portfolio" # the subpath of your site, e.g. /blog
#url: "http://sinjoysaha.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Sinjoy Saha
user_description: 
user_title: Engineer
email: sinjoysaha555@gmail.com
twitter_username: SinjoySaha
linkedin_username:  sinjoysaha
github_username: sinjoysaha
hackerrank_username: sinjoysaha
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
